//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Viewer
{
    using System;
    using System.Collections.Generic;
    
    public partial class EntryAlias
    {
        public int EntryId { get; set; }
        public string Alias { get; set; }
        public int RelationType { get; set; }
    
        public virtual Entry Entry { get; set; }
    }
}
